# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1eff51c906a9cb1fc1b4d548a403a4f1d062f068320c0f646c4cef8ac4da14bc6e9452b3fca7859fb46c249520ee0369f845ae18d5e117d63e096cb84c3294f1

test:
  secret_key_base: 59bde2289320a82f7c002923afdf5e1420e7dc1a6844e6b579b9e0355c9fd9c47a067dff4be4eda488c40bbed2f1dd89ca63c9d16fbcfbdb8d58525d548bdd5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
